refactored pokedex api

diff --git a/pokemondb_scraper/Dockerfile b/pokemondb_scraper/Dockerfile
--- a/pokemondb_scraper/Dockerfile
+++ b/pokemondb_scraper/Dockerfile
@@ -9,6 +9,8 @@ COPY . .
 
 ENV PYTHONPATH=/app
 
+RUN ls -la /app/ && ls -la /app/pokemondb_scraper/ || echo "pokemondb_scraper dir MISSING"
+
 RUN dos2unix entrypoint.sh && chmod +x entrypoint.sh
 
 ENTRYPOINT ["./entrypoint.sh"]
